### PR TITLE
adding a run once DaemonSet example

### PR DESCRIPTION
**Pull request by luisdavim**
This was inspired by http://blog.itaysk.com/2017/12/26/the-single-use-daemonset-pattern-and-prepulling-images-in-kubernetes

### CODE REVIEW

**Comment by luisdavim** [comment]
I've signed the CLA

**Comment by luisdavim** [comment]
@enisoc could you take a look at this?  Anything you'd like me to change? Thanks.

**Comment by enisoc** [comment]
I haven't had a chance to fully review this yet (mainly I just want to try it out), but overall I like the idea. Thanks!

One quick comment: Can you change `*.enisoc.com` to either some domain you own, or `example.com`? I only put `enisoc.com` on the other examples because I wrote them. I don't want to take credit for your example. :)

I'll try to do a full review on this tomorrow.

**Comment by luisdavim** [comment]
I've updated the domain, I didn't even noticed that before as I've started this from a copy of the `indexedjob` example.

**Pull request merged**
